### ISSUE TITLE
Import divisions for users

### ISSUE THREAD

**Issue by ahtotruu** [e-i-o/cms#6]
When divisions are used, the import tool allows the task metadata to include a list of divisions for which the task will be available, but does not recognize a division setting for user import.

**Comment by prandla** [comment]
fixed in a978ee1f5c9da1dc78a2651b30cf1293c6193100
use like
```
users:
  - username: eio
    password: password
    division: G
 ```
